### ISSUE TITLE
Add NIST 800-128

### ISSUE THREAD

**Issue by gregelin** [GovReady/compliancekbs#10]
Title: Guide for Security-Focused Configuration Management of Information Systems

Especially noteworthy is Appendix I, page I-5, I-6 "Attachment 1 Security Impact Worksheet". These are questions by Security family to ask oneself about the impact of a change. 

Terms: worksheet, configuration management, security impact worksheet

**Comment by MCupp93** [comment]
Having a few issues with this document and the omb memo. The yaml files are created but when trying to upload to document cloud it is not allowing me to do it with either of these. The text that it is giving me is as follows. 

Traceback (most recent call last):
  File "upload-document-to-documentcloud.py", line 20, in <module>
    from server import get_documentcloud_document_id
  File "/home/vagrant/server.py", line 62, in <module>
    for res in rtyaml.load_all(f): # a YAML file may contain more than one document
AttributeError: 'module' object has no attribute 'load_all'

**Comment by gregelin** [comment]
Try uploading documents manually to DocumentCloud.
